import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { usePeopleContext } from "../components/contexts/PeopleContext";
import { PeopleSearch } from "../components/PeopleSearch";

const Home: NextPage = () => {
  const { people } = usePeopleContext();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <a href="/">Air Logo Here</a>
      </header>

      <main>
        <h1>The Person Finder</h1>
        <p>
          If you just can’t find someone and need to know what they look like,
          you’ve come to the right place! Just type the name of the person you
          are looking for below into the search box!
        </p>
        <PeopleSearch people={people} />
      </main>
    </div>
  );
};

export default Home;
